# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1423274833);
user_pref("app.update.lastUpdateTime.background-update-timer", 1423508362);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1423274953);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1423508242);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1423508122);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131205075310");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 867);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20131205075310");
user_pref("browser.startup.homepage_override.mstone", "26.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3,\"addons\":4}");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1423508054148");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1423508054440");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1423594454440");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1417744155005");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1417803293173");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1416442294231");
user_pref("datareporting.sessions.current.activeTicks", 16);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 891);
user_pref("datareporting.sessions.current.main", 32);
user_pref("datareporting.sessions.current.sessionRestored", 953);
user_pref("datareporting.sessions.current.startTime", "1423508460686");
user_pref("datareporting.sessions.current.totalTime", 81);
user_pref("datareporting.sessions.currentIndex", 10);
user_pref("datareporting.sessions.previous.9", "{\"s\":1423507991951,\"a\":4,\"t\":467,\"c\":true,\"m\":38,\"fp\":910,\"sr\":1153}");
user_pref("datareporting.sessions.prunedIndex", 8);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"30.0\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"30.0\"}");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("extensions.blocklist.pingCountTotal", 5);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:26.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150106.01");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1386265009000,\"rdfTime\":1386263224000}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"/Users/david/Library/Application Support/Firefox/Profiles/20wpnd01.default/extensions/firebug@software.joehewitt.com.xpi\",\"mtime\":1423508453000}}}]");
user_pref("extensions.lastAppVersion", "26.0");
user_pref("extensions.lastPlatformVersion", "26.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sce.bypass_domain_mismatch", true);
user_pref("extensions.sce.bypass_domains", "[\".ifixyourmom.com\",\".cominor.com\"]");
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://search/skip%20ssl%20cert");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20131205075310");
user_pref("gecko.mstone", "26.0");
user_pref("idle.lastDailyNotification", 1417744200);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1423508054);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.OCSP.enabled", 0);
user_pref("security.OCSP.require", true);
user_pref("security.disable_button.openCertManager", false);
user_pref("security.disable_button.openDeviceManager", false);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1416443240);
user_pref("toolkit.startup.last_success", 1423508460);
user_pref("toolkit.telemetry.previousBuildID", "20131205075310");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1425836574);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
