#!/bin/sh

ssh_command_file=~/.ssh_command
if [ ! -f "$ssh_command_file" ]; then
   echo "Missing ssh command file:"
   echo "Save the ssh command necessary to access cominor to the local path: $ssh_command_file"
   exit 1
fi

port_file=.selenium_port
if [ ! -f ~/$port_file ]; then
   port=$((4400 + $RANDOM % 101))
   echo "Saving random port number: $port to cominor: ~/$port_file"
   `cat $ssh_command_file` "echo $port > ~/$port_file"
   echo $port > ~/$port_file
fi
