[distributor]
reject-unsupported-caps = true # Reject a request immediately if the Grid does not support the requested capability.

[node]
detect-drivers = false # Ignore local drivers and use the ones specified in the driver configuration section.

[[node.driver-configuration]]
display-name = "chrome"
webdriver-path = "./chromedriver"
stereotype = '{"browserName": "chrome", "browserVersion": "<version>"}' # Browser version is not used by the Grid, but it is used by the tests to determine which browser to use.