#!/bin/bash

# Crash if something breaks
set -e

# ensure we have the prerequisites (ssh command, port, ...)
. ./_setup || exit 1

port=`cat ~/.selenium_port`
ssh_command=`cat ~/.ssh_command`

ssh_runner() {
  echo
  echo "Forwarding port: remote:$port to localhost:4444"
  ssh_line="$ssh_command -TNn -R $port:localhost:4444"
  while true
  do
    $ssh_line
    echo "Restarting SSH..."
  done
}

# kill my whole process group on exit
# This kills the child process spun off below
trap "kill -- -$$" EXIT

# Spin off watcher for SSH
ssh_runner&

echo
echo Launching Selenium...
java -jar selenium-server-standalone*
