#!/bin/sh

# ensure we have the prerequisites (ssh command, port, ...)
source ./_setup || exit 1

port=`cat ~/.selenium_port`
ssh_command=`cat ~/.ssh_command`

echo
echo "Forwarding port: remote:$port to localhost:4444"
ssh_line="$ssh_command -TNf -R $port:localhost:4444"
$ssh_line >/dev/null /2>&1
# Get pid of ssh background process -- tricky
ssh_pid=`ps -A -o "pid command" | grep -F "$ssh_line" | head -n 1 | awk '{print $1}'`
# kill the ssh process on exit
trap "kill $ssh_pid" EXIT

echo
echo Launching Selenium...
java -jar selenium-server-standalone* -firefoxProfileTemplate ./firefox-profile/ -Dphantomjs.binary.path=phantomjs*/bin/phantomjs
